version: 0.2

env:
  variables:
    EVENT_SYSTEM_DEV_BUCKET: "dk.vurdst.ice.artifacts"
    EVENT_SYSTEM_DEV_VERSION: "0.15.0"

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - echo $EVENT_SYSTEM_DEV_LOCATION
      - printenv
  pre_build:
    commands:
      - echo Verify artifacts
      - aws s3 cp "s3://$EVENT_SYSTEM_DEV_BUCKET/event-system-$EVENT_SYSTEM_DEV_VERSION-sam.yaml" event-system.yaml
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - aws cloudformation deploy --no-fail-on-empty-changeset --template-file event-system.yaml --stack-name EventSystem --capabilities CAPABILITY_IAM --region eu-west-1 --parameter-overrides Stage=dev Bucket=$EVENT_SYSTEM_DEV_LOCATION Key="event-system-$EVENT_SYSTEM_DEV_VERSION-standalone.jar" Role=arn:aws:iam::593176282530:role/lambda-s3-execution-role
