version: 0.2

env:
  variables:
    EVENT_SYSTEM_DEV_BUCKET: "dk.vurdst.ice.artifacts"
    EVENT_SYSTEM_DEV_VERSION: "0.15.0"
    AGGREGATE_SAG_DEV_VERSION: "0.1.0"

phases:
  pre_build:
    commands:
      - echo Verify artifacts
      - aws s3 cp "s3://$EVENT_SYSTEM_DEV_BUCKET/event-system-$EVENT_SYSTEM_DEV_VERSION-sam.yaml" event-system.yaml
      - aws s3 cp "s3://$EVENT_SYSTEM_DEV_BUCKET/aggregate-sag-$AGGREGATE_SAG_DEV_VERSION-sam.yaml" aggregate-sag.yaml
  post_build:
    commands:
      - echo Build completed on `date`
      - aws cloudformation deploy --no-fail-on-empty-changeset --template-file event-system.yaml --stack-name EventSystem --capabilities CAPABILITY_IAM --region eu-west-1 --parameter-overrides Stage=dev Bucket=$EVENT_SYSTEM_DEV_BUCKET Key="event-system-$EVENT_SYSTEM_DEV_VERSION-standalone.jar" Role=arn:aws:iam::593176282530:role/lambda-s3-execution-role
      - aws cloudformation deploy --no-fail-on-empty-changeset --template-file aggregate-sag.yaml --stack-name AggregateSag --capabilities CAPABILITY_IAM --region eu-west-1 --parameter-overrides Stage=dev Bucket=$EVENT_SYSTEM_DEV_BUCKET Key="event-system-$AGGREGATE_SAG_DEV_VERSION-standalone.jar" Role=arn:aws:iam::593176282530:role/lambda-s3-execution-role
