defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: wilson208/circleci-awscli

    steps:
      - checkout

      - run: cat ./deploy.desc >> $BASH_ENV

      - run: aws s3 cp "s3://dk.vurdst.ice.artifacts/aggregate-sag-lambda-$DEV_VERSION.jar" .

      - run: ls

  deploy-dev:
    <<: *defaults
    docker:
      - image: wilson208/circleci-awscli

    steps:
      - run: aws cloudformation list-stacks --region eu-west-1

  deploy-test:
    <<: *defaults
    docker:
      - image: wilson208/circleci-awscli

    steps:
      - run: aws cloudformation list-stacks --region eu-west-1

workflows:
  version: 2
  deploy-line:
    jobs:
      - build
      - hold-dev:
          type: approval
      - deploy-dev:
          requires:
            - hold-dev
      - hold-test:
          type: approval
      - deploy-test:
          requires:
            - hold-test
