defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: wilson208/circleci-awscl

    steps:
      - checkout

      - run: aws cloudformation list-stacks
 
  deploy-dev:
     <<: *defaults
    docker:
      - image: wilson208/circleci-awscl
    
    steps:
      - run: aws cloudformation list-stacks

  deploy-test:
     <<: *defaults
    docker:
      - image: wilson208/circleci-awscl

    steps:
      - run: aws cloudformation list-stacks

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - hold-dev:
          type: approval
      - deploy-dev
      - hold-test:
          type: approval
      - deploy-test
