defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  deploy-test:
    <<: *defaults
    docker:
      - image: wilson208/circleci-awscli

    steps:
      - checkout

      - run: cat ./deploy.desc >> $BASH_ENV

      - run: aws s3 cp "s3://dk.vurdst.ice.artifacts/aggregate-sag-lambda-$AGGR_SAG_LAMBDA_TEST_VERSION.yaml" .

      - run: aws cloudformation deploy --template-file "aggregate-sag-lambda-$AGGR_SAG_LAMBDA_TEST_VERSION.yaml" --stack-name aggrsag-test --capabilities CAPABILITY_IAM --region eu-west-1 --parameter-overrides Stage=test

  deploy-preprod:
    <<: *defaults
    docker:
      - image: wilson208/circleci-awscli

    steps:
      - checkout

      - run: cat ./deploy.desc >> $BASH_ENV

      - run: aws s3 cp "s3://dk.vurdst.ice.artifacts/aggregate-sag-lambda-$AGGR_SAG_LAMBDA_PREPROD_VERSION.yaml" .

      - run: aws cloudformation deploy --template-file "aggregate-sag-lambda-$AGGR_SAG_LAMBDA_PREPROD_VERSION.yaml" --stack-name aggrsag-preprod --capabilities CAPABILITY_IAM --region eu-west-1 --parameter-overrides Stage=preprod

workflows:
  version: 2
  deploy-line:
    jobs:
      - hold-test:
          type: approval
      - deploy-test:
          requires:
            - hold-test
      - hold-preprod:
          type: approval
      - deploy-preprod:
          requires:
            - hold-preprod
